server:
  port: 8080
  servlet:
    context-path: /flutter
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/flutter-app"
    password: manhden123
    username: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true